In [6]:
import numpy as np

import torch 
import torch.nn as nn
import torch.nn.functional as F

from torchvision.models import alexnet

In [7]:
from data import VOT19
vot = VOT19()
video,boxes = vot.__getitem__(31)

In [8]:
from gct import GCT
gct = GCT(10)
video2 = video[:30,:,:,:]

In [9]:
out = gct.forward(video2[25,:,:,:],video2[15:25,:,:,:])

X torch.Size([1, 256, 11, 8]) Z torch.Size([10, 256, 11, 8])
X torch.Size([1, 256, 88]) Z torch.Size([10, 256, 88])
X^ torch.Size([1, 256, 88])
A_1 torch.Size([880, 880]) 
V_1 torch.Size([1, 256, 88])
V_x torch.Size([1, 256, 88])
tensor([[-203650.]], grad_fn=<MmBackward>)
tensor([[861996.2500]], grad_fn=<MmBackward>)
tensor([[-203792.6719]], grad_fn=<MmBackward>)
tensor([[861482.0625]], grad_fn=<MmBackward>)
tensor([[-203844.3750]], grad_fn=<MmBackward>)
tensor([[861804.2500]], grad_fn=<MmBackward>)
tensor([[-204219.5312]], grad_fn=<MmBackward>)
tensor([[861562.2500]], grad_fn=<MmBackward>)
tensor([[-203695.8438]], grad_fn=<MmBackward>)
tensor([[861582.8750]], grad_fn=<MmBackward>)
tensor([[-203690.9688]], grad_fn=<MmBackward>)
tensor([[861219.7500]], grad_fn=<MmBackward>)
tensor([[-203999.2344]], grad_fn=<MmBackward>)
tensor([[861853.1875]], grad_fn=<MmBackward>)
tensor([[-204114.2500]], grad_fn=<MmBackward>)
tensor([[861482.5625]], grad_fn=<MmBackward>)
tensor([[-203987.4844]], grad_

tensor([[-52047.5508]], grad_fn=<MmBackward>)
tensor([[-1066757.1250]], grad_fn=<MmBackward>)
tensor([[-51958.9688]], grad_fn=<MmBackward>)
tensor([[-1066379.1250]], grad_fn=<MmBackward>)
tensor([[-52403.5547]], grad_fn=<MmBackward>)
tensor([[-1066864.]], grad_fn=<MmBackward>)
tensor([[-52440.2852]], grad_fn=<MmBackward>)
tensor([[-1067506.5000]], grad_fn=<MmBackward>)
tensor([[-52001.6484]], grad_fn=<MmBackward>)
tensor([[-1066932.5000]], grad_fn=<MmBackward>)
tensor([[-52829.8945]], grad_fn=<MmBackward>)
tensor([[-1066984.5000]], grad_fn=<MmBackward>)
tensor([[-52445.5039]], grad_fn=<MmBackward>)
tensor([[-1067339.]], grad_fn=<MmBackward>)
tensor([[-51757.0977]], grad_fn=<MmBackward>)
tensor([[-1067151.1250]], grad_fn=<MmBackward>)
tensor([[-52159.8164]], grad_fn=<MmBackward>)
tensor([[-1066830.]], grad_fn=<MmBackward>)
tensor([[-52123.1836]], grad_fn=<MmBackward>)
tensor([[-1067276.1250]], grad_fn=<MmBackward>)
tensor([[-51942.0664]], grad_fn=<MmBackward>)
tensor([[-1066917.1250]], 

tensor([[-204259.0312]], grad_fn=<MmBackward>)
tensor([[861987.1250]], grad_fn=<MmBackward>)
tensor([[-203889.5469]], grad_fn=<MmBackward>)
tensor([[861807.5000]], grad_fn=<MmBackward>)
tensor([[-203930.4375]], grad_fn=<MmBackward>)
tensor([[861768.8750]], grad_fn=<MmBackward>)
tensor([[-204071.4219]], grad_fn=<MmBackward>)
tensor([[861961.2500]], grad_fn=<MmBackward>)
tensor([[-203871.3281]], grad_fn=<MmBackward>)
tensor([[861725.3125]], grad_fn=<MmBackward>)
tensor([[-204059.9375]], grad_fn=<MmBackward>)
tensor([[861708.]], grad_fn=<MmBackward>)
tensor([[-204263.7500]], grad_fn=<MmBackward>)
tensor([[861788.1875]], grad_fn=<MmBackward>)
tensor([[-204025.2188]], grad_fn=<MmBackward>)
tensor([[861419.8750]], grad_fn=<MmBackward>)
tensor([[-203892.2812]], grad_fn=<MmBackward>)
tensor([[861928.3125]], grad_fn=<MmBackward>)
tensor([[-204284.0781]], grad_fn=<MmBackward>)
tensor([[861562.8125]], grad_fn=<MmBackward>)
tensor([[-204063.1719]], grad_fn=<MmBackward>)
tensor([[861751.2500]], gra

tensor([[861853.4375]], grad_fn=<MmBackward>)
tensor([[-203927.3438]], grad_fn=<MmBackward>)
tensor([[861965.6875]], grad_fn=<MmBackward>)
tensor([[-204113.3281]], grad_fn=<MmBackward>)
tensor([[861797.5000]], grad_fn=<MmBackward>)
tensor([[-204010.5938]], grad_fn=<MmBackward>)
tensor([[861966.6875]], grad_fn=<MmBackward>)
tensor([[-204226.8125]], grad_fn=<MmBackward>)
tensor([[861655.1250]], grad_fn=<MmBackward>)
tensor([[-204271.3281]], grad_fn=<MmBackward>)
tensor([[861519.6875]], grad_fn=<MmBackward>)
tensor([[-203912.7500]], grad_fn=<MmBackward>)
tensor([[862044.5000]], grad_fn=<MmBackward>)
tensor([[-203782.5469]], grad_fn=<MmBackward>)
tensor([[861695.8750]], grad_fn=<MmBackward>)
tensor([[-203993.5938]], grad_fn=<MmBackward>)
tensor([[861897.4375]], grad_fn=<MmBackward>)
tensor([[-203637.9688]], grad_fn=<MmBackward>)
tensor([[861767.1250]], grad_fn=<MmBackward>)
tensor([[-203991.2188]], grad_fn=<MmBackward>)
tensor([[861888.1250]], grad_fn=<MmBackward>)
tensor([[-203698.8750]],

tensor([[-52295.8320]], grad_fn=<MmBackward>)
tensor([[-1067094.8750]], grad_fn=<MmBackward>)
tensor([[-52082.0742]], grad_fn=<MmBackward>)
tensor([[-1066698.2500]], grad_fn=<MmBackward>)
tensor([[-52178.9570]], grad_fn=<MmBackward>)
tensor([[-1067020.2500]], grad_fn=<MmBackward>)
tensor([[-52092.5352]], grad_fn=<MmBackward>)
tensor([[-1066778.2500]], grad_fn=<MmBackward>)
tensor([[-52003.3516]], grad_fn=<MmBackward>)
tensor([[-1066400.5000]], grad_fn=<MmBackward>)
tensor([[-52448.5742]], grad_fn=<MmBackward>)
tensor([[-1066886.7500]], grad_fn=<MmBackward>)
tensor([[-52485.9883]], grad_fn=<MmBackward>)
tensor([[-1067528.2500]], grad_fn=<MmBackward>)
tensor([[-52047.5859]], grad_fn=<MmBackward>)
tensor([[-1066953.7500]], grad_fn=<MmBackward>)
tensor([[-52874.8516]], grad_fn=<MmBackward>)
tensor([[-1067008.7500]], grad_fn=<MmBackward>)
tensor([[-52490.8320]], grad_fn=<MmBackward>)
tensor([[-1067362.]], grad_fn=<MmBackward>)
tensor([[-51801.2891]], grad_fn=<MmBackward>)
tensor([[-1067173.

tensor([[-204206.0781]], grad_fn=<MmBackward>)
tensor([[861587.8750]], grad_fn=<MmBackward>)
tensor([[-203790.9062]], grad_fn=<MmBackward>)
tensor([[861338.6250]], grad_fn=<MmBackward>)
tensor([[-204193.1094]], grad_fn=<MmBackward>)
tensor([[861601.1250]], grad_fn=<MmBackward>)
tensor([[-204352.5781]], grad_fn=<MmBackward>)
tensor([[861556.4375]], grad_fn=<MmBackward>)
tensor([[-1066785.5000]], grad_fn=<MmBackward>)
tensor([[-52072.5430]], grad_fn=<MmBackward>)
tensor([[-1066904.3750]], grad_fn=<MmBackward>)
tensor([[-52630.9688]], grad_fn=<MmBackward>)
tensor([[-1067035.]], grad_fn=<MmBackward>)
tensor([[-52287.4219]], grad_fn=<MmBackward>)
tensor([[-1067380.5000]], grad_fn=<MmBackward>)
tensor([[-52533.3555]], grad_fn=<MmBackward>)
tensor([[-1066785.6250]], grad_fn=<MmBackward>)
tensor([[-52492.0547]], grad_fn=<MmBackward>)
tensor([[-1066789.7500]], grad_fn=<MmBackward>)
tensor([[-52971.6914]], grad_fn=<MmBackward>)
tensor([[-1067182.3750]], grad_fn=<MmBackward>)
tensor([[-52253.1875

tensor([[-204071.5781]], grad_fn=<MmBackward>)
tensor([[861757.3750]], grad_fn=<MmBackward>)
tensor([[-203776.]], grad_fn=<MmBackward>)
tensor([[861828.6250]], grad_fn=<MmBackward>)
tensor([[-203424.8281]], grad_fn=<MmBackward>)
tensor([[861414.4375]], grad_fn=<MmBackward>)
tensor([[-203892.2656]], grad_fn=<MmBackward>)
tensor([[861435.6250]], grad_fn=<MmBackward>)
tensor([[-204511.4062]], grad_fn=<MmBackward>)
tensor([[861775.3750]], grad_fn=<MmBackward>)
tensor([[-203951.2812]], grad_fn=<MmBackward>)
tensor([[861040.7500]], grad_fn=<MmBackward>)
tensor([[-204086.7031]], grad_fn=<MmBackward>)
tensor([[861397.8125]], grad_fn=<MmBackward>)
tensor([[-204315.2812]], grad_fn=<MmBackward>)
tensor([[862067.1875]], grad_fn=<MmBackward>)
tensor([[-204165.]], grad_fn=<MmBackward>)
tensor([[861660.9375]], grad_fn=<MmBackward>)
tensor([[-203827.8906]], grad_fn=<MmBackward>)
tensor([[861686.6250]], grad_fn=<MmBackward>)
tensor([[-204315.5469]], grad_fn=<MmBackward>)
tensor([[861879.0625]], grad_fn

tensor([[-53289.6836]], grad_fn=<MmBackward>)
tensor([[-1067411.6250]], grad_fn=<MmBackward>)
tensor([[-52904.3516]], grad_fn=<MmBackward>)
tensor([[-1067764.7500]], grad_fn=<MmBackward>)
tensor([[-52215.2305]], grad_fn=<MmBackward>)
tensor([[-1067576.6250]], grad_fn=<MmBackward>)
tensor([[-52618.6094]], grad_fn=<MmBackward>)
tensor([[-1067255.5000]], grad_fn=<MmBackward>)
tensor([[-52582.8125]], grad_fn=<MmBackward>)
tensor([[-1067701.5000]], grad_fn=<MmBackward>)
tensor([[-52401.2539]], grad_fn=<MmBackward>)
tensor([[-1067342.8750]], grad_fn=<MmBackward>)
tensor([[-52585.6562]], grad_fn=<MmBackward>)
tensor([[-1067396.8750]], grad_fn=<MmBackward>)
tensor([[-52615.2305]], grad_fn=<MmBackward>)
tensor([[-1067534.5000]], grad_fn=<MmBackward>)
tensor([[-52445.1523]], grad_fn=<MmBackward>)
tensor([[-1067364.7500]], grad_fn=<MmBackward>)
tensor([[-52695.2227]], grad_fn=<MmBackward>)
tensor([[-1067558.7500]], grad_fn=<MmBackward>)
tensor([[-52639.8828]], grad_fn=<MmBackward>)
tensor([[-1067

tensor([[-1067587.6250]], grad_fn=<MmBackward>)
tensor([[-52610.7852]], grad_fn=<MmBackward>)
tensor([[-1067511.1250]], grad_fn=<MmBackward>)
tensor([[-52449.2109]], grad_fn=<MmBackward>)
tensor([[-1067721.2500]], grad_fn=<MmBackward>)
tensor([[-52795.4062]], grad_fn=<MmBackward>)
tensor([[-1067811.1250]], grad_fn=<MmBackward>)
tensor([[-52937.0977]], grad_fn=<MmBackward>)
tensor([[-1067429.]], grad_fn=<MmBackward>)
tensor([[-52370.8594]], grad_fn=<MmBackward>)
tensor([[-1067320.5000]], grad_fn=<MmBackward>)
tensor([[-52715.9766]], grad_fn=<MmBackward>)
tensor([[-1067498.]], grad_fn=<MmBackward>)
tensor([[-52502.4609]], grad_fn=<MmBackward>)
tensor([[-1067102.1250]], grad_fn=<MmBackward>)
tensor([[-52597.4766]], grad_fn=<MmBackward>)
tensor([[-1067425.7500]], grad_fn=<MmBackward>)
tensor([[-52513.5625]], grad_fn=<MmBackward>)
tensor([[-1067184.7500]], grad_fn=<MmBackward>)
tensor([[-52424.2383]], grad_fn=<MmBackward>)
tensor([[-1066807.2500]], grad_fn=<MmBackward>)
tensor([[-52867.1289

tensor([[-204269.1562]], grad_fn=<MmBackward>)
tensor([[861531.3750]], grad_fn=<MmBackward>)
tensor([[-203910.8750]], grad_fn=<MmBackward>)
tensor([[862056.5625]], grad_fn=<MmBackward>)
tensor([[-203778.2031]], grad_fn=<MmBackward>)
tensor([[861707.2500]], grad_fn=<MmBackward>)
tensor([[-203989.9688]], grad_fn=<MmBackward>)
tensor([[861910.8750]], grad_fn=<MmBackward>)
tensor([[-203635.2188]], grad_fn=<MmBackward>)
tensor([[861780.6250]], grad_fn=<MmBackward>)
tensor([[-203989.0312]], grad_fn=<MmBackward>)
tensor([[861900.8125]], grad_fn=<MmBackward>)
tensor([[-203695.7031]], grad_fn=<MmBackward>)
tensor([[861972.6875]], grad_fn=<MmBackward>)
tensor([[-203342.8594]], grad_fn=<MmBackward>)
tensor([[861556.3750]], grad_fn=<MmBackward>)
tensor([[-203810.6719]], grad_fn=<MmBackward>)
tensor([[861578.4375]], grad_fn=<MmBackward>)
tensor([[-204428.0625]], grad_fn=<MmBackward>)
tensor([[861918.6250]], grad_fn=<MmBackward>)
tensor([[-203869.1562]], grad_fn=<MmBackward>)
tensor([[861184.2500]],

tensor([[-52396.7969]], grad_fn=<MmBackward>)
tensor([[-1067113.5000]], grad_fn=<MmBackward>)
tensor([[-52307.6289]], grad_fn=<MmBackward>)
tensor([[-1066735.7500]], grad_fn=<MmBackward>)
tensor([[-52750.5000]], grad_fn=<MmBackward>)
tensor([[-1067218.8750]], grad_fn=<MmBackward>)
tensor([[-52788.2422]], grad_fn=<MmBackward>)
tensor([[-1067862.5000]], grad_fn=<MmBackward>)
tensor([[-52350.2773]], grad_fn=<MmBackward>)
tensor([[-1067287.8750]], grad_fn=<MmBackward>)
tensor([[-53176.9492]], grad_fn=<MmBackward>)
tensor([[-1067343.6250]], grad_fn=<MmBackward>)
tensor([[-52793.6953]], grad_fn=<MmBackward>)
tensor([[-1067695.3750]], grad_fn=<MmBackward>)
tensor([[-52104.0312]], grad_fn=<MmBackward>)
tensor([[-1067508.6250]], grad_fn=<MmBackward>)
tensor([[-52508.4922]], grad_fn=<MmBackward>)
tensor([[-1067186.5000]], grad_fn=<MmBackward>)
tensor([[-52471.9883]], grad_fn=<MmBackward>)
tensor([[-1067633.]], grad_fn=<MmBackward>)
tensor([[-52288.9531]], grad_fn=<MmBackward>)
tensor([[-1067273.

tensor([[-204376.1875]], grad_fn=<MmBackward>)
tensor([[861409.]], grad_fn=<MmBackward>)
tensor([[-203959.2969]], grad_fn=<MmBackward>)
tensor([[861159.6250]], grad_fn=<MmBackward>)
tensor([[-204363.0781]], grad_fn=<MmBackward>)
tensor([[861421.2500]], grad_fn=<MmBackward>)
tensor([[-204521.7812]], grad_fn=<MmBackward>)
tensor([[861377.5000]], grad_fn=<MmBackward>)
tensor([[-1066720.5000]], grad_fn=<MmBackward>)
tensor([[-51972.0312]], grad_fn=<MmBackward>)
tensor([[-1066839.3750]], grad_fn=<MmBackward>)
tensor([[-52529.5312]], grad_fn=<MmBackward>)
tensor([[-1066969.7500]], grad_fn=<MmBackward>)
tensor([[-52186.8125]], grad_fn=<MmBackward>)
tensor([[-1067314.5000]], grad_fn=<MmBackward>)
tensor([[-52432.3984]], grad_fn=<MmBackward>)
tensor([[-1066719.]], grad_fn=<MmBackward>)
tensor([[-52390.8203]], grad_fn=<MmBackward>)
tensor([[-1066725.5000]], grad_fn=<MmBackward>)
tensor([[-52871.4375]], grad_fn=<MmBackward>)
tensor([[-1067117.2500]], grad_fn=<MmBackward>)
tensor([[-52153.4258]], 

tensor([[-204197.6719]], grad_fn=<MmBackward>)
tensor([[861774.7500]], grad_fn=<MmBackward>)
tensor([[-204095.0312]], grad_fn=<MmBackward>)
tensor([[861943.5625]], grad_fn=<MmBackward>)
tensor([[-204311.0625]], grad_fn=<MmBackward>)
tensor([[861633.6250]], grad_fn=<MmBackward>)
tensor([[-204355.9844]], grad_fn=<MmBackward>)
tensor([[861496.8125]], grad_fn=<MmBackward>)
tensor([[-203996.5469]], grad_fn=<MmBackward>)
tensor([[862023.2500]], grad_fn=<MmBackward>)
tensor([[-203865.7188]], grad_fn=<MmBackward>)
tensor([[861672.6250]], grad_fn=<MmBackward>)
tensor([[-204078.8125]], grad_fn=<MmBackward>)
tensor([[861876.1250]], grad_fn=<MmBackward>)
tensor([[-203721.7969]], grad_fn=<MmBackward>)
tensor([[861745.9375]], grad_fn=<MmBackward>)
tensor([[-204074.7812]], grad_fn=<MmBackward>)
tensor([[861866.3125]], grad_fn=<MmBackward>)
tensor([[-203782.5156]], grad_fn=<MmBackward>)
tensor([[861936.7500]], grad_fn=<MmBackward>)
tensor([[-203429.7969]], grad_fn=<MmBackward>)
tensor([[861520.8750]],

tensor([[-1067592.2500]], grad_fn=<MmBackward>)
tensor([[-52650.4688]], grad_fn=<MmBackward>)
tensor([[-1067364.3750]], grad_fn=<MmBackward>)
tensor([[-52425.7422]], grad_fn=<MmBackward>)
tensor([[-1066875.5000]], grad_fn=<MmBackward>)
tensor([[-52740.0039]], grad_fn=<MmBackward>)
tensor([[-1067363.5000]], grad_fn=<MmBackward>)
tensor([[-52482.8320]], grad_fn=<MmBackward>)
tensor([[-1067595.]], grad_fn=<MmBackward>)
tensor([[-52389.6719]], grad_fn=<MmBackward>)
tensor([[-204100.6719]], grad_fn=<MmBackward>)
tensor([[861571.6250]], grad_fn=<MmBackward>)
tensor([[-204243.8438]], grad_fn=<MmBackward>)
tensor([[861056.5000]], grad_fn=<MmBackward>)
tensor([[-204295.4844]], grad_fn=<MmBackward>)
tensor([[861378.1250]], grad_fn=<MmBackward>)
tensor([[-204670.]], grad_fn=<MmBackward>)
tensor([[861135.4375]], grad_fn=<MmBackward>)
tensor([[-204145.7500]], grad_fn=<MmBackward>)
tensor([[861158.3750]], grad_fn=<MmBackward>)
tensor([[-204142.7969]], grad_fn=<MmBackward>)
tensor([[860794.2500]], gr

tensor([[-1067256.6250]], grad_fn=<MmBackward>)
tensor([[-52566.7383]], grad_fn=<MmBackward>)
tensor([[-1067492.3750]], grad_fn=<MmBackward>)
tensor([[-52450.4648]], grad_fn=<MmBackward>)
tensor([[-1067608.6250]], grad_fn=<MmBackward>)
tensor([[-52627.7773]], grad_fn=<MmBackward>)
tensor([[-1067531.8750]], grad_fn=<MmBackward>)
tensor([[-52466.3438]], grad_fn=<MmBackward>)
tensor([[-1067740.5000]], grad_fn=<MmBackward>)
tensor([[-52810.3516]], grad_fn=<MmBackward>)
tensor([[-1067829.8750]], grad_fn=<MmBackward>)
tensor([[-52952.9844]], grad_fn=<MmBackward>)
tensor([[-1067447.6250]], grad_fn=<MmBackward>)
tensor([[-52386.6680]], grad_fn=<MmBackward>)
tensor([[-1067340.1250]], grad_fn=<MmBackward>)
tensor([[-52731.9297]], grad_fn=<MmBackward>)
tensor([[-1067518.5000]], grad_fn=<MmBackward>)
tensor([[-52518.9414]], grad_fn=<MmBackward>)
tensor([[-1067122.2500]], grad_fn=<MmBackward>)
tensor([[-52615.9102]], grad_fn=<MmBackward>)
tensor([[-1067446.]], grad_fn=<MmBackward>)
tensor([[-52528.

tensor([[861624.6875]], grad_fn=<MmBackward>)
tensor([[-203631.7812]], grad_fn=<MmBackward>)
tensor([[861208.6250]], grad_fn=<MmBackward>)
tensor([[-204097.9844]], grad_fn=<MmBackward>)
tensor([[861230.8125]], grad_fn=<MmBackward>)
tensor([[-204716.7656]], grad_fn=<MmBackward>)
tensor([[861571.2500]], grad_fn=<MmBackward>)
tensor([[-204157.7812]], grad_fn=<MmBackward>)
tensor([[860836.8750]], grad_fn=<MmBackward>)
tensor([[-204292.5469]], grad_fn=<MmBackward>)
tensor([[861192.3750]], grad_fn=<MmBackward>)
tensor([[-204521.0469]], grad_fn=<MmBackward>)
tensor([[861861.6250]], grad_fn=<MmBackward>)
tensor([[-204372.2500]], grad_fn=<MmBackward>)
tensor([[861455.2500]], grad_fn=<MmBackward>)
tensor([[-204035.0625]], grad_fn=<MmBackward>)
tensor([[861480.1875]], grad_fn=<MmBackward>)
tensor([[-204522.6875]], grad_fn=<MmBackward>)
tensor([[861673.]], grad_fn=<MmBackward>)
tensor([[-204153.1250]], grad_fn=<MmBackward>)
tensor([[861493.1875]], grad_fn=<MmBackward>)
tensor([[-204192.1250]], gra

tensor([[-52719.9844]], grad_fn=<MmBackward>)
tensor([[-1067819.5000]], grad_fn=<MmBackward>)
tensor([[-52627.3203]], grad_fn=<MmBackward>)
tensor([[-203861.4688]], grad_fn=<MmBackward>)
tensor([[861801.3125]], grad_fn=<MmBackward>)
tensor([[-204004.7188]], grad_fn=<MmBackward>)
tensor([[861287.6250]], grad_fn=<MmBackward>)
tensor([[-204055.6719]], grad_fn=<MmBackward>)
tensor([[861607.8125]], grad_fn=<MmBackward>)
tensor([[-204430.8438]], grad_fn=<MmBackward>)
tensor([[861366.6875]], grad_fn=<MmBackward>)
tensor([[-203906.5781]], grad_fn=<MmBackward>)
tensor([[861389.1250]], grad_fn=<MmBackward>)
tensor([[-203903.9688]], grad_fn=<MmBackward>)
tensor([[861024.6250]], grad_fn=<MmBackward>)
tensor([[-204210.2188]], grad_fn=<MmBackward>)
tensor([[861657.3750]], grad_fn=<MmBackward>)
tensor([[-204324.2812]], grad_fn=<MmBackward>)
tensor([[861287.6875]], grad_fn=<MmBackward>)
tensor([[-204198.5312]], grad_fn=<MmBackward>)
tensor([[861328.5625]], grad_fn=<MmBackward>)
tensor([[-204170.2188]]

tensor([[-1067269.1250]], grad_fn=<MmBackward>)
tensor([[-52342.4180]], grad_fn=<MmBackward>)
tensor([[-1067358.5000]], grad_fn=<MmBackward>)
tensor([[-52484.9141]], grad_fn=<MmBackward>)
tensor([[-1066976.2500]], grad_fn=<MmBackward>)
tensor([[-51919.1289]], grad_fn=<MmBackward>)
tensor([[-1066869.]], grad_fn=<MmBackward>)
tensor([[-52263.7891]], grad_fn=<MmBackward>)
tensor([[-1067047.8750]], grad_fn=<MmBackward>)
tensor([[-52050.5820]], grad_fn=<MmBackward>)
tensor([[-1066652.]], grad_fn=<MmBackward>)
tensor([[-52146.3125]], grad_fn=<MmBackward>)
tensor([[-1066974.3750]], grad_fn=<MmBackward>)
tensor([[-52061.6328]], grad_fn=<MmBackward>)
tensor([[-1066732.6250]], grad_fn=<MmBackward>)
tensor([[-51971.8984]], grad_fn=<MmBackward>)
tensor([[-1066355.5000]], grad_fn=<MmBackward>)
tensor([[-52417.5430]], grad_fn=<MmBackward>)
tensor([[-1066839.1250]], grad_fn=<MmBackward>)
tensor([[-52453.6758]], grad_fn=<MmBackward>)
tensor([[-1067482.8750]], grad_fn=<MmBackward>)
tensor([[-52015.9961

tensor([[860655.6875]], grad_fn=<MmBackward>)
tensor([[-204586.6562]], grad_fn=<MmBackward>)
tensor([[861164.]], grad_fn=<MmBackward>)
tensor([[-204978.9375]], grad_fn=<MmBackward>)
tensor([[860798.4375]], grad_fn=<MmBackward>)
tensor([[-204758.2031]], grad_fn=<MmBackward>)
tensor([[860985.8125]], grad_fn=<MmBackward>)
tensor([[-204343.0625]], grad_fn=<MmBackward>)
tensor([[860735.4375]], grad_fn=<MmBackward>)
tensor([[-204744.3438]], grad_fn=<MmBackward>)
tensor([[860998.2500]], grad_fn=<MmBackward>)
tensor([[-204903.8125]], grad_fn=<MmBackward>)
tensor([[860955.6250]], grad_fn=<MmBackward>)
tensor([[-1066707.3750]], grad_fn=<MmBackward>)
tensor([[-51877.9805]], grad_fn=<MmBackward>)
tensor([[-1066828.8750]], grad_fn=<MmBackward>)
tensor([[-52435.4531]], grad_fn=<MmBackward>)
tensor([[-1066957.5000]], grad_fn=<MmBackward>)
tensor([[-52092.1914]], grad_fn=<MmBackward>)
tensor([[-1067304.2500]], grad_fn=<MmBackward>)
tensor([[-52338.4609]], grad_fn=<MmBackward>)
tensor([[-1066708.]], gr

tensor([[861492.8125]], grad_fn=<MmBackward>)
tensor([[-204173.2656]], grad_fn=<MmBackward>)
tensor([[861696.]], grad_fn=<MmBackward>)
tensor([[-203816.0938]], grad_fn=<MmBackward>)
tensor([[861564.7500]], grad_fn=<MmBackward>)
tensor([[-204172.9219]], grad_fn=<MmBackward>)
tensor([[861685.5000]], grad_fn=<MmBackward>)
tensor([[-203877.8438]], grad_fn=<MmBackward>)
tensor([[861757.1875]], grad_fn=<MmBackward>)
tensor([[-203524.9531]], grad_fn=<MmBackward>)
tensor([[861341.5000]], grad_fn=<MmBackward>)
tensor([[-203992.3594]], grad_fn=<MmBackward>)
tensor([[861362.8750]], grad_fn=<MmBackward>)
tensor([[-204610.6406]], grad_fn=<MmBackward>)
tensor([[861702.8125]], grad_fn=<MmBackward>)
tensor([[-204051.8750]], grad_fn=<MmBackward>)
tensor([[860968.6875]], grad_fn=<MmBackward>)
tensor([[-204187.2188]], grad_fn=<MmBackward>)
tensor([[861324.6875]], grad_fn=<MmBackward>)
tensor([[-204415.4531]], grad_fn=<MmBackward>)
tensor([[861994.2500]], grad_fn=<MmBackward>)
tensor([[-204266.8594]], gra

tensor([[-1067287.3750]], grad_fn=<MmBackward>)
tensor([[-52409.1367]], grad_fn=<MmBackward>)
tensor([[-1067517.6250]], grad_fn=<MmBackward>)
tensor([[-52314.0469]], grad_fn=<MmBackward>)
tensor([[-203843.1562]], grad_fn=<MmBackward>)
tensor([[861759.2500]], grad_fn=<MmBackward>)
tensor([[-203986.2812]], grad_fn=<MmBackward>)
tensor([[861244.2500]], grad_fn=<MmBackward>)
tensor([[-204037.8125]], grad_fn=<MmBackward>)
tensor([[861565.2500]], grad_fn=<MmBackward>)
tensor([[-204413.6562]], grad_fn=<MmBackward>)
tensor([[861324.0625]], grad_fn=<MmBackward>)
tensor([[-203889.4688]], grad_fn=<MmBackward>)
tensor([[861346.6875]], grad_fn=<MmBackward>)
tensor([[-203886.0625]], grad_fn=<MmBackward>)
tensor([[860981.7500]], grad_fn=<MmBackward>)
tensor([[-204191.8281]], grad_fn=<MmBackward>)
tensor([[861614.0625]], grad_fn=<MmBackward>)
tensor([[-204307.3438]], grad_fn=<MmBackward>)
tensor([[861244.8750]], grad_fn=<MmBackward>)
tensor([[-204180.5938]], grad_fn=<MmBackward>)
tensor([[861286.0625]

tensor([[-1067170.]], grad_fn=<MmBackward>)
tensor([[-52101.6797]], grad_fn=<MmBackward>)
tensor([[-1067381.1250]], grad_fn=<MmBackward>)
tensor([[-52446.4062]], grad_fn=<MmBackward>)
tensor([[-1067468.3750]], grad_fn=<MmBackward>)
tensor([[-52587.7227]], grad_fn=<MmBackward>)
tensor([[-1067086.6250]], grad_fn=<MmBackward>)
tensor([[-52022.1523]], grad_fn=<MmBackward>)
tensor([[-1066977.5000]], grad_fn=<MmBackward>)
tensor([[-52366.3555]], grad_fn=<MmBackward>)
tensor([[-1067158.1250]], grad_fn=<MmBackward>)
tensor([[-52153.3047]], grad_fn=<MmBackward>)
tensor([[-1066761.1250]], grad_fn=<MmBackward>)
tensor([[-52250.1641]], grad_fn=<MmBackward>)
tensor([[-1067082.6250]], grad_fn=<MmBackward>)
tensor([[-52164.0312]], grad_fn=<MmBackward>)
tensor([[-1066842.2500]], grad_fn=<MmBackward>)
tensor([[-52075.9375]], grad_fn=<MmBackward>)
tensor([[-1066465.6250]], grad_fn=<MmBackward>)
tensor([[-52520.0117]], grad_fn=<MmBackward>)
tensor([[-1066948.6250]], grad_fn=<MmBackward>)
tensor([[-52557.

tensor([[-1067289.]], grad_fn=<MmBackward>)
tensor([[-52430.0430]], grad_fn=<MmBackward>)
tensor([[-1066695.6250]], grad_fn=<MmBackward>)
tensor([[-52386.9688]], grad_fn=<MmBackward>)
tensor([[-1066700.1250]], grad_fn=<MmBackward>)
tensor([[-52866.3594]], grad_fn=<MmBackward>)
tensor([[-1067093.8750]], grad_fn=<MmBackward>)
tensor([[-52148.6445]], grad_fn=<MmBackward>)
tensor([[-1067198.8750]], grad_fn=<MmBackward>)
tensor([[-52540.2539]], grad_fn=<MmBackward>)
tensor([[-1067025.3750]], grad_fn=<MmBackward>)
tensor([[-52509.3008]], grad_fn=<MmBackward>)
tensor([[-1066970.]], grad_fn=<MmBackward>)
tensor([[-52248.6367]], grad_fn=<MmBackward>)
tensor([[-1066882.5000]], grad_fn=<MmBackward>)
tensor([[-52222.2891]], grad_fn=<MmBackward>)
tensor([[-1067116.2500]], grad_fn=<MmBackward>)
tensor([[-52106.9961]], grad_fn=<MmBackward>)
tensor([[-1067234.]], grad_fn=<MmBackward>)
tensor([[-52283.3398]], grad_fn=<MmBackward>)
tensor([[-1067157.6250]], grad_fn=<MmBackward>)
tensor([[-52122.1523]], 

tensor([[861959.1250]], grad_fn=<MmBackward>)
tensor([[-204017.9688]], grad_fn=<MmBackward>)
tensor([[861588.7500]], grad_fn=<MmBackward>)
tensor([[-203891.7969]], grad_fn=<MmBackward>)
tensor([[861630.0625]], grad_fn=<MmBackward>)
tensor([[-203865.8750]], grad_fn=<MmBackward>)
tensor([[861874.8125]], grad_fn=<MmBackward>)
tensor([[-203735.4219]], grad_fn=<MmBackward>)
tensor([[861855.7500]], grad_fn=<MmBackward>)
tensor([[-203915.0781]], grad_fn=<MmBackward>)
tensor([[861969.5000]], grad_fn=<MmBackward>)
tensor([[-204099.8281]], grad_fn=<MmBackward>)
tensor([[861798.5000]], grad_fn=<MmBackward>)
tensor([[-203998.2500]], grad_fn=<MmBackward>)
tensor([[861967.5000]], grad_fn=<MmBackward>)
tensor([[-204212.8750]], grad_fn=<MmBackward>)
tensor([[861657.3125]], grad_fn=<MmBackward>)
tensor([[-204259.5938]], grad_fn=<MmBackward>)
tensor([[861521.1875]], grad_fn=<MmBackward>)
tensor([[-203900.8750]], grad_fn=<MmBackward>)
tensor([[862046.9375]], grad_fn=<MmBackward>)
tensor([[-203768.9375]],

tensor([[-52079.6055]], grad_fn=<MmBackward>)
tensor([[-1067023.7500]], grad_fn=<MmBackward>)
tensor([[-52263.0234]], grad_fn=<MmBackward>)
tensor([[-1067079.3750]], grad_fn=<MmBackward>)
tensor([[-52293.6523]], grad_fn=<MmBackward>)
tensor([[-1067217.6250]], grad_fn=<MmBackward>)
tensor([[-52121.7695]], grad_fn=<MmBackward>)
tensor([[-1067048.1250]], grad_fn=<MmBackward>)
tensor([[-52372.9453]], grad_fn=<MmBackward>)
tensor([[-1067239.8750]], grad_fn=<MmBackward>)
tensor([[-52317.7852]], grad_fn=<MmBackward>)
tensor([[-1067423.8750]], grad_fn=<MmBackward>)
tensor([[-52254.4453]], grad_fn=<MmBackward>)
tensor([[-1067245.1250]], grad_fn=<MmBackward>)
tensor([[-52685.7812]], grad_fn=<MmBackward>)
tensor([[-1067082.6250]], grad_fn=<MmBackward>)
tensor([[-52151.2500]], grad_fn=<MmBackward>)
tensor([[-1067447.5000]], grad_fn=<MmBackward>)
tensor([[-52540.9609]], grad_fn=<MmBackward>)
tensor([[-1067218.]], grad_fn=<MmBackward>)
tensor([[-52314.5117]], grad_fn=<MmBackward>)
tensor([[-1066730.

tensor([[-1067157.7500]], grad_fn=<MmBackward>)
tensor([[-52202.9258]], grad_fn=<MmBackward>)
tensor([[-1067080.5000]], grad_fn=<MmBackward>)
tensor([[-52041.9766]], grad_fn=<MmBackward>)
tensor([[-1067289.8750]], grad_fn=<MmBackward>)
tensor([[-52387.6719]], grad_fn=<MmBackward>)
tensor([[-1067381.1250]], grad_fn=<MmBackward>)
tensor([[-52529.6133]], grad_fn=<MmBackward>)
tensor([[-1066998.5000]], grad_fn=<MmBackward>)
tensor([[-51962.7109]], grad_fn=<MmBackward>)
tensor([[-1066889.8750]], grad_fn=<MmBackward>)
tensor([[-52306.7812]], grad_fn=<MmBackward>)
tensor([[-1067068.2500]], grad_fn=<MmBackward>)
tensor([[-52095.1289]], grad_fn=<MmBackward>)
tensor([[-1066672.5000]], grad_fn=<MmBackward>)
tensor([[-52192.6875]], grad_fn=<MmBackward>)
tensor([[-1066995.3750]], grad_fn=<MmBackward>)
tensor([[-52106.2148]], grad_fn=<MmBackward>)
tensor([[-1066753.5000]], grad_fn=<MmBackward>)
tensor([[-52017.7148]], grad_fn=<MmBackward>)
tensor([[-1066374.1250]], grad_fn=<MmBackward>)
tensor([[-52

In [10]:
out

tensor([[[[nan]]]], grad_fn=<MkldnnConvolutionBackward>)